#!/usr/bin/env bash
# SCRIPTPATH=$( cd "$(dirname "$0")" ; pwd -P )
# echo $SCRIPTPATH
cd "$(dirname "$0")"
vim -Nu <(cat << EOF
filetype off
set rtp+=~/.vim/plugged/vader.vim
set rtp+=../
filetype plugin indent on
syntax enable
EOF
) '+Vader! **/*.vader'
