language: node_js
node_js:
  - 6

env:
  global:
    - DEPS=$HOME/deps
    - PATH=$DEPS/bin:$PATH

before_install: |
  git clone --depth 1 https://github.com/vim/vim
  cd vim
  ./configure --prefix=$DEPS --with-features=huge --disable-gui
  make
  make install
  vim --version
  cd -

before_script:
  - git clone https://github.com/junegunn/vader.vim.git

script:
  - npm test
  - ./test/run-on-travis
